#!/bin/bash

# Global variable to store update status
UPDATE_STATUS=""

# Function to update the repository
update_repo() {
    UPDATE_STATUS="updating"
    REPO_DIR="$PREFIX/share/test"
    SCRIPT_NAME="hello"
    BIN_DIR="$PREFIX/bin"

    cd "$REPO_DIR" || exit 1
    
    # Run git pull origin and parse the output to show only relevant lines
    if output=$(git pull origin $(git rev-parse --abbrev-ref HEAD) 2>&1 | grep -E 'Updating|Already up to date'); then
        # Check if the script exists in the bin directory
        if [ -L "$BIN_DIR/$SCRIPT_NAME" ]; then
            echo "Script Updated Successfully..."
        else
            echo "Script Failed to Update..."
        fi
    else
        echo "ERROR"
    fi
    if [ true ]; then
        sleep 0.3
        echo "updated"
        exit 0 && exec "$0"
    else
        sleep 0.3
        echo "failed"
    fi
}

# Function to print hello message
hello() {
    echo "Hello AJ7"
}

# Function to print hii message
hii() {
    echo "Hii AJ7"
}

# Function to check for updates in the repository
check_update() {
    REPO_DIR="$PREFIX/share/test"
    SCRIPT_NAME="hello"
    REPO_URL="https://github.com/Aj-Seven/test"

    # Check if the repository folder exists
    if [ ! -d "$REPO_DIR" ]; then
        git clone "$REPO_URL" "$REPO_DIR" > /dev/null 2>&1 || { UPDATE_STATUS="failed"; return; }
    fi

    # Fetch updates forcefully
    cd "$REPO_DIR" || { UPDATE_STATUS="failed"; return; }
    git fetch --force origin > /dev/null 2>&1

    # Get the current branch
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    # Check if the local branch is behind the remote branch
    if [ $(git rev-list HEAD...origin/$current_branch --count) -gt 0 ]; then
sleep 0.5
        echo "available"
    else
sleep 0.5
        echo "up-to-date"
    fi
}

# Main function
main() {

    echo -e "\n"
    echo -e "UPDATE MONITOR:"
    echo -e "$UPDATE_STATUS"

    echo "Select an option:"
    echo "1. Check update status"
    echo "2. Update repository"
    echo "3. hello"
    echo "4. hII"
    echo "0. Exit"

    read -p "Enter your choice: " choice

    case $choice in
        1) UPDATE_STATUS=$(check_update)
            ;;
        2) UPDATE_STATUS=$(update_repo)
            ;;
        3) hello ;;
        4) hii ;;
        0)
            echo "Exiting..."
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter a number between 0 and 4."
            ;;
    esac
}

# Set the default PREFIX if not provided
if [ -z "$PREFIX" ]; then
    PREFIX="/data/data/com.termux/files/usr/"
fi

# Execute the main function in a loop
while true; do
    check_update
sleep 0.3
    main
done
