#!/bin/bash

# Function to check for updates in the repository
check_update() {
    REPO_DIR="$PREFIX/share/test"
    SCRIPT_NAME="your_script.sh"
    REPO_URL="https://github.com/Aj-Seven/test"

    # Check if the repository folder exists
    if [ ! -d "$REPO_DIR" ]; then
        echo "Repository folder not found, cloning repository..."
        git clone "$REPO_URL" "$REPO_DIR" > /dev/null 2>&1 || { echo "Failed to clone repository"; exit 1; }
    fi

    # Fetch updates forcefully
    cd "$REPO_DIR" || exit 1
    git fetch --force origin > /dev/null 2>&1

    # Get the current branch
    current_branch=$(git rev-parse --abbrev-ref HEAD)

    # Check if the local branch is behind the remote branch
    if [ $(git rev-list HEAD...origin/$current_branch --count) -gt 0 ]; then
        echo "Updates available in $current_branch"
        # Ask the user if they want to update the script
        read -p "Do you want to update the script? (Y/N): " choice
        case "$choice" in
            y|Y) update_repo ;;
            n|N) echo "No updates applied";;
            *) echo "Invalid choice. No updates applied.";;
        esac
    else
        echo "Up-to-date in $current_branch"
    fi
}

# Function to update the repository
update_repo() {
    REPO_DIR="$PREFIX/share/test"
    SCRIPT_NAME="your_script.sh"
    BIN_DIR="$PREFIX/bin"

    cd "$REPO_DIR" || exit 1
    
    # Run git pull origin and parse the output to show only relevant lines
    if output=$(git pull origin $(git rev-parse --abbrev-ref HEAD) 2>&1 | grep -E 'Updating|Already up to date'); then
        echo "$output"
        # Check if the script exists in the bin directory
        if [ -L "$BIN_DIR/$SCRIPT_NAME" ]; then
            echo "Script linked to $BIN_DIR/$SCRIPT_NAME"
        else
            echo "Script not linked to $BIN_DIR/$SCRIPT_NAME"
        fi
    else
        echo "Error occurred while updating the repository"
    fi
}

# Function to show updated content without restarting the script
auto() {
    # Call main function
    main
}

# Function to print hello message
hello() {
    echo "Hello AJseven"
}

# Function to print hii message
hii() {
    echo "Hii AJ7"
}

# Main function
main() {
    echo "Select an option:"
    echo "1. Check update status"
    echo "2. Update repository"
    echo "3. hello"
    echo "4. hII"
    echo "0. Exit"

    read -p "Enter your choice: " choice

    case $choice in
        1) check_update  || { echo "Failed to check for updates"; exit 1; }
            ;;
        2) update_repo
            ;;
        3) hello
            ;;
        4) hii
            ;;
        0)
            echo "Exiting..."
            exit 0
            ;;
        *)
            echo "Invalid choice. Please enter a number between 0 and 4."
            ;;
    esac
}

# Execute the main function
main
